// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateBusinessPhone(ctx context.Context, arg CreateBusinessPhoneParams) (WhatsappBusinessPhone, error)
	GetBusinessPhoneByCompanyId(ctx context.Context, companyID int64) (WhatsappBusinessPhone, error)
	UpdateBusinessPhone(ctx context.Context, arg UpdateBusinessPhoneParams) (WhatsappBusinessPhone, error)
}

var _ Querier = (*Queries)(nil)
