// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whatsapp_messaging.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const bulkUpsertConversations = `-- name: BulkUpsertConversations :exec
INSERT INTO whatsapp_messaging.whatsapp_conversations (
    company_id, jid, name, unread_count, is_group, profile_picture_url
) 
SELECT 
    unnest($1::bigint[]) as company_id,
    unnest($2::text[]) as jid,
    unnest($3::text[]) as name,
    unnest($4::int[]) as unread_count,
    unnest($5::boolean[]) as is_group,
    unnest($6::text[]) as profile_picture_url
ON CONFLICT (company_id, jid) 
DO UPDATE SET
    name = EXCLUDED.name,
    unread_count = EXCLUDED.unread_count,
    is_group = EXCLUDED.is_group,
    profile_picture_url = EXCLUDED.profile_picture_url,
    last_message_timestamp = CASE 
        WHEN EXCLUDED.last_message_timestamp > whatsapp_messaging.whatsapp_conversations.last_message_timestamp 
        OR whatsapp_messaging.whatsapp_conversations.last_message_timestamp IS NULL
        THEN EXCLUDED.last_message_timestamp
        ELSE whatsapp_messaging.whatsapp_conversations.last_message_timestamp
    END,
    modified_at = NOW()
`

type BulkUpsertConversationsParams struct {
	CompanyIds         []int64  `json:"company_ids"`
	Jids               []string `json:"jids"`
	Names              []string `json:"names"`
	UnreadCounts       []int32  `json:"unread_counts"`
	IsGroups           []bool   `json:"is_groups"`
	ProfilePictureUrls []string `json:"profile_picture_urls"`
}

func (q *Queries) BulkUpsertConversations(ctx context.Context, arg BulkUpsertConversationsParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpsertConversations,
		pq.Array(arg.CompanyIds),
		pq.Array(arg.Jids),
		pq.Array(arg.Names),
		pq.Array(arg.UnreadCounts),
		pq.Array(arg.IsGroups),
		pq.Array(arg.ProfilePictureUrls),
	)
	return err
}

const bulkUpsertMessages = `-- name: BulkUpsertMessages :exec
WITH input_data AS (
    SELECT DISTINCT ON (company_id, conversation_jid, timestamp, from_me, remote_jid)
        company_id, conversation_jid, remote_jid, from_me,
        message_type, message_text, media_url, media_caption, status,
        timestamp, received_at, edited_at, is_forwarded, is_deleted
    FROM (
        SELECT 
            unnest($1::bigint[]) as company_id,
            unnest($2::text[]) as conversation_jid,
            unnest($3::text[]) as remote_jid,
            unnest($4::boolean[]) as from_me,
            unnest($5::text[]) as message_type,
            unnest($6::text[]) as message_text,
            unnest($7::text[]) as media_url,
            unnest($8::text[]) as media_caption,
            unnest($9::text[]) as status,
            unnest($10::timestamptz[]) as timestamp,
            unnest($11::timestamptz[]) as received_at,
            unnest($12::timestamptz[]) as edited_at,
            unnest($13::boolean[]) as is_forwarded,
            unnest($14::boolean[]) as is_deleted
    ) AS raw_input
    ORDER BY company_id, conversation_jid, timestamp, from_me, remote_jid, timestamp DESC
)
INSERT INTO whatsapp_messaging.whatsapp_messages (
    company_id, conversation_jid, remote_jid, from_me,
    message_type, message_text, media_url, media_caption, status,
    timestamp, received_at, edited_at, is_forwarded, is_deleted
) 
SELECT company_id, conversation_jid, remote_jid, from_me, message_type, message_text, media_url, media_caption, status, timestamp, received_at, edited_at, is_forwarded, is_deleted FROM input_data
ON CONFLICT (company_id, conversation_jid, timestamp, from_me, remote_jid)
DO UPDATE SET
    message_text = EXCLUDED.message_text,
    media_url = EXCLUDED.media_url,
    media_caption = EXCLUDED.media_caption,
    status = EXCLUDED.status,
    edited_at = EXCLUDED.edited_at,
    is_forwarded = EXCLUDED.is_forwarded,
    is_deleted = EXCLUDED.is_deleted,
    modified_at = NOW()
`

type BulkUpsertMessagesParams struct {
	CompanyIds       []int64     `json:"company_ids"`
	ConversationJids []string    `json:"conversation_jids"`
	RemoteJids       []string    `json:"remote_jids"`
	FromMes          []bool      `json:"from_mes"`
	MessageTypes     []string    `json:"message_types"`
	MessageTexts     []string    `json:"message_texts"`
	MediaUrls        []string    `json:"media_urls"`
	MediaCaptions    []string    `json:"media_captions"`
	Statuses         []string    `json:"statuses"`
	Timestamps       []time.Time `json:"timestamps"`
	ReceivedAts      []time.Time `json:"received_ats"`
	EditedAts        []time.Time `json:"edited_ats"`
	IsForwardeds     []bool      `json:"is_forwardeds"`
	IsDeleteds       []bool      `json:"is_deleteds"`
}

func (q *Queries) BulkUpsertMessages(ctx context.Context, arg BulkUpsertMessagesParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpsertMessages,
		pq.Array(arg.CompanyIds),
		pq.Array(arg.ConversationJids),
		pq.Array(arg.RemoteJids),
		pq.Array(arg.FromMes),
		pq.Array(arg.MessageTypes),
		pq.Array(arg.MessageTexts),
		pq.Array(arg.MediaUrls),
		pq.Array(arg.MediaCaptions),
		pq.Array(arg.Statuses),
		pq.Array(arg.Timestamps),
		pq.Array(arg.ReceivedAts),
		pq.Array(arg.EditedAts),
		pq.Array(arg.IsForwardeds),
		pq.Array(arg.IsDeleteds),
	)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO 
  whatsapp_messaging.whatsapp_conversations (
    company_id, 
    jid, 
    name,
    unread_count,
    is_group,
    profile_picture_url
	) 
VALUES (
  $1, $2, $3, $4, $5, $6
  )
RETURNING id
`

type CreateConversationParams struct {
	CompanyID         int64          `json:"company_id"`
	Jid               string         `json:"jid"`
	Name              sql.NullString `json:"name"`
	UnreadCount       sql.NullInt32  `json:"unread_count"`
	IsGroup           sql.NullBool   `json:"is_group"`
	ProfilePictureUrl sql.NullString `json:"profile_picture_url"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.CompanyID,
		arg.Jid,
		arg.Name,
		arg.UnreadCount,
		arg.IsGroup,
		arg.ProfilePictureUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO 
  whatsapp_messaging.whatsapp_messages (
    company_id, 
    conversation_jid, 
    remote_jid,
    from_me,
    message_type,
    message_text,
    media_url,
    media_caption,
    status,
    timestamp,
    received_at,
    edited_at,
    is_forwarded,
    is_deleted
	) 
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
  )
RETURNING id
`

type CreateMessageParams struct {
	CompanyID       int64          `json:"company_id"`
	ConversationJid string         `json:"conversation_jid"`
	RemoteJid       string         `json:"remote_jid"`
	FromMe          sql.NullBool   `json:"from_me"`
	MessageType     string         `json:"message_type"`
	MessageText     sql.NullString `json:"message_text"`
	MediaUrl        sql.NullString `json:"media_url"`
	MediaCaption    sql.NullString `json:"media_caption"`
	Status          sql.NullString `json:"status"`
	Timestamp       time.Time      `json:"timestamp"`
	ReceivedAt      sql.NullTime   `json:"received_at"`
	EditedAt        sql.NullTime   `json:"edited_at"`
	IsForwarded     sql.NullBool   `json:"is_forwarded"`
	IsDeleted       sql.NullBool   `json:"is_deleted"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.CompanyID,
		arg.ConversationJid,
		arg.RemoteJid,
		arg.FromMe,
		arg.MessageType,
		arg.MessageText,
		arg.MediaUrl,
		arg.MediaCaption,
		arg.Status,
		arg.Timestamp,
		arg.ReceivedAt,
		arg.EditedAt,
		arg.IsForwarded,
		arg.IsDeleted,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT
  id,
  company_id,
  jid,
  name,
  unread_count,
  is_group,
  profile_picture_url,
  last_message_timestamp
FROM
  whatsapp_messaging.whatsapp_conversations
WHERE
  id = $1
LIMIT 1
`

type GetConversationByIDRow struct {
	ID                   int64          `json:"id"`
	CompanyID            int64          `json:"company_id"`
	Jid                  string         `json:"jid"`
	Name                 sql.NullString `json:"name"`
	UnreadCount          sql.NullInt32  `json:"unread_count"`
	IsGroup              sql.NullBool   `json:"is_group"`
	ProfilePictureUrl    sql.NullString `json:"profile_picture_url"`
	LastMessageTimestamp sql.NullTime   `json:"last_message_timestamp"`
}

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (GetConversationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i GetConversationByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Jid,
		&i.Name,
		&i.UnreadCount,
		&i.IsGroup,
		&i.ProfilePictureUrl,
		&i.LastMessageTimestamp,
	)
	return i, err
}

const getConversationByJID = `-- name: GetConversationByJID :one
SELECT
  id,
  company_id,
  jid,
  name,
  unread_count,
  is_group,
  profile_picture_url,
  last_message_timestamp
FROM
  whatsapp_messaging.whatsapp_conversations
WHERE
  company_id = $1 AND 
  jid = $2
LIMIT 1
`

type GetConversationByJIDParams struct {
	CompanyID int64  `json:"company_id"`
	Jid       string `json:"jid"`
}

type GetConversationByJIDRow struct {
	ID                   int64          `json:"id"`
	CompanyID            int64          `json:"company_id"`
	Jid                  string         `json:"jid"`
	Name                 sql.NullString `json:"name"`
	UnreadCount          sql.NullInt32  `json:"unread_count"`
	IsGroup              sql.NullBool   `json:"is_group"`
	ProfilePictureUrl    sql.NullString `json:"profile_picture_url"`
	LastMessageTimestamp sql.NullTime   `json:"last_message_timestamp"`
}

func (q *Queries) GetConversationByJID(ctx context.Context, arg GetConversationByJIDParams) (GetConversationByJIDRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationByJID, arg.CompanyID, arg.Jid)
	var i GetConversationByJIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Jid,
		&i.Name,
		&i.UnreadCount,
		&i.IsGroup,
		&i.ProfilePictureUrl,
		&i.LastMessageTimestamp,
	)
	return i, err
}

const getMessagesByConversationJID = `-- name: GetMessagesByConversationJID :many
SELECT
  id, 
  company_id, 
  conversation_jid, 
  remote_jid,
  from_me,
  message_type,
  message_text,
  media_url,
  media_caption,
  status,
  timestamp,
  received_at,
  edited_at,
  is_forwarded,
  is_deleted
FROM
  whatsapp_messaging.whatsapp_messages
WHERE
  conversation_jid = $1
ORDER BY
  received_at DESC
LIMIT 
  $2
OFFSET 
  $3
`

type GetMessagesByConversationJIDParams struct {
	ConversationJid string `json:"conversation_jid"`
	Limit           int32  `json:"limit"`
	Offset          int32  `json:"offset"`
}

type GetMessagesByConversationJIDRow struct {
	ID              int64          `json:"id"`
	CompanyID       int64          `json:"company_id"`
	ConversationJid string         `json:"conversation_jid"`
	RemoteJid       string         `json:"remote_jid"`
	FromMe          sql.NullBool   `json:"from_me"`
	MessageType     string         `json:"message_type"`
	MessageText     sql.NullString `json:"message_text"`
	MediaUrl        sql.NullString `json:"media_url"`
	MediaCaption    sql.NullString `json:"media_caption"`
	Status          sql.NullString `json:"status"`
	Timestamp       time.Time      `json:"timestamp"`
	ReceivedAt      sql.NullTime   `json:"received_at"`
	EditedAt        sql.NullTime   `json:"edited_at"`
	IsForwarded     sql.NullBool   `json:"is_forwarded"`
	IsDeleted       sql.NullBool   `json:"is_deleted"`
}

func (q *Queries) GetMessagesByConversationJID(ctx context.Context, arg GetMessagesByConversationJIDParams) ([]GetMessagesByConversationJIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversationJID, arg.ConversationJid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByConversationJIDRow{}
	for rows.Next() {
		var i GetMessagesByConversationJIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ConversationJid,
			&i.RemoteJid,
			&i.FromMe,
			&i.MessageType,
			&i.MessageText,
			&i.MediaUrl,
			&i.MediaCaption,
			&i.Status,
			&i.Timestamp,
			&i.ReceivedAt,
			&i.EditedAt,
			&i.IsForwarded,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
