version: '3.9'

services:
  # customer-svc:
  #     image: EdoRguez/customer-svc
  #     ports:
  #       - "50052:50052"
  #     environment:
  #       - PORT=:50052
  #       - DB_URL=postgres://postgres:postgres@customer-db:5432/customer_svc
  #     depends_on:
  #       - customer-db
  #     restart: always

  customer-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${CUSTOMER_SVC_DB}
      - POSTGRES_USER=${CUSTOMER_SVC_DB_USER}
      - POSTGRES_PASSWORD=${CUSTOMER_SVC_DB_PASSWORD}
    restart: always
