// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type CustomerCustomer struct {
	ID                   int64          `json:"id"`
	CompanyID            int64          `json:"company_id"`
	FirstName            string         `json:"first_name"`
	LastName             sql.NullString `json:"last_name"`
	Email                sql.NullString `json:"email"`
	Phone                sql.NullString `json:"phone"`
	IdentificationNumber string         `json:"identification_number"`
	IdentificationType   string         `json:"identification_type"`
	CreatedAt            time.Time      `json:"created_at"`
	ModifiedAt           time.Time      `json:"modified_at"`
}
