// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: company.proto

package company

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NameFormatUrl string                 `protobuf:"bytes,2,opt,name=name_format_url,json=nameFormatUrl,proto3" json:"name_format_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCompanyRequest) GetNameFormatUrl() string {
	if x != nil {
		return x.NameFormatUrl
	}
	return ""
}

type CreateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyResponse) Reset() {
	*x = CreateCompanyResponse{}
	mi := &file_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyResponse) ProtoMessage() {}

func (x *CreateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyResponse.ProtoReflect.Descriptor instead.
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompanyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCompanyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateCompanyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompanyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCompanyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameFormatUrl   string                 `protobuf:"bytes,3,opt,name=name_format_url,json=nameFormatUrl,proto3" json:"name_format_url,omitempty"`
	ImageUrl        *string                `protobuf:"bytes,4,opt,name=imageUrl,proto3,oneof" json:"imageUrl,omitempty"`
	PlanId          int64                  `protobuf:"varint,5,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	LastPaymentDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastPaymentDate,proto3" json:"lastPaymentDate,omitempty"`
	Status          int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCompanyResponse) Reset() {
	*x = GetCompanyResponse{}
	mi := &file_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyResponse) ProtoMessage() {}

func (x *GetCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{3}
}

func (x *GetCompanyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCompanyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompanyResponse) GetNameFormatUrl() string {
	if x != nil {
		return x.NameFormatUrl
	}
	return ""
}

func (x *GetCompanyResponse) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *GetCompanyResponse) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *GetCompanyResponse) GetLastPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPaymentDate
	}
	return nil
}

func (x *GetCompanyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCompanyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCompanyByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyByNameRequest) Reset() {
	*x = GetCompanyByNameRequest{}
	mi := &file_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyByNameRequest) ProtoMessage() {}

func (x *GetCompanyByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyByNameRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{4}
}

func (x *GetCompanyByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCompanyByNameResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameFormatUrl   string                 `protobuf:"bytes,3,opt,name=name_format_url,json=nameFormatUrl,proto3" json:"name_format_url,omitempty"`
	ImageUrl        *string                `protobuf:"bytes,4,opt,name=imageUrl,proto3,oneof" json:"imageUrl,omitempty"`
	PlanId          int64                  `protobuf:"varint,5,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	LastPaymentDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastPaymentDate,proto3" json:"lastPaymentDate,omitempty"`
	Status          int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCompanyByNameResponse) Reset() {
	*x = GetCompanyByNameResponse{}
	mi := &file_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyByNameResponse) ProtoMessage() {}

func (x *GetCompanyByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyByNameResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyByNameResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{5}
}

func (x *GetCompanyByNameResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCompanyByNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompanyByNameResponse) GetNameFormatUrl() string {
	if x != nil {
		return x.NameFormatUrl
	}
	return ""
}

func (x *GetCompanyByNameResponse) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *GetCompanyByNameResponse) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *GetCompanyByNameResponse) GetLastPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPaymentDate
	}
	return nil
}

func (x *GetCompanyByNameResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCompanyByNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCompanyByNameUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameUrl       string                 `protobuf:"bytes,1,opt,name=nameUrl,proto3" json:"nameUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyByNameUrlRequest) Reset() {
	*x = GetCompanyByNameUrlRequest{}
	mi := &file_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyByNameUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyByNameUrlRequest) ProtoMessage() {}

func (x *GetCompanyByNameUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyByNameUrlRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyByNameUrlRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{6}
}

func (x *GetCompanyByNameUrlRequest) GetNameUrl() string {
	if x != nil {
		return x.NameUrl
	}
	return ""
}

type GetCompanyByNameUrlResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameFormatUrl   string                 `protobuf:"bytes,3,opt,name=name_format_url,json=nameFormatUrl,proto3" json:"name_format_url,omitempty"`
	ImageUrl        *string                `protobuf:"bytes,4,opt,name=imageUrl,proto3,oneof" json:"imageUrl,omitempty"`
	PlanId          int64                  `protobuf:"varint,5,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	LastPaymentDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastPaymentDate,proto3" json:"lastPaymentDate,omitempty"`
	Status          int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCompanyByNameUrlResponse) Reset() {
	*x = GetCompanyByNameUrlResponse{}
	mi := &file_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyByNameUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyByNameUrlResponse) ProtoMessage() {}

func (x *GetCompanyByNameUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyByNameUrlResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyByNameUrlResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{7}
}

func (x *GetCompanyByNameUrlResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCompanyByNameUrlResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompanyByNameUrlResponse) GetNameFormatUrl() string {
	if x != nil {
		return x.NameFormatUrl
	}
	return ""
}

func (x *GetCompanyByNameUrlResponse) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *GetCompanyByNameUrlResponse) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *GetCompanyByNameUrlResponse) GetLastPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPaymentDate
	}
	return nil
}

func (x *GetCompanyByNameUrlResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCompanyByNameUrlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesRequest) Reset() {
	*x = GetCompaniesRequest{}
	mi := &file_company_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesRequest) ProtoMessage() {}

func (x *GetCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesRequest.ProtoReflect.Descriptor instead.
func (*GetCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{8}
}

func (x *GetCompaniesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCompaniesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*GetCompanyResponse  `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesResponse) Reset() {
	*x = GetCompaniesResponse{}
	mi := &file_company_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesResponse) ProtoMessage() {}

func (x *GetCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesResponse.ProtoReflect.Descriptor instead.
func (*GetCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{9}
}

func (x *GetCompaniesResponse) GetCompanies() []*GetCompanyResponse {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *GetCompaniesResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCompaniesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameFormatUrl string                 `protobuf:"bytes,3,opt,name=name_format_url,json=nameFormatUrl,proto3" json:"name_format_url,omitempty"`
	Image         []byte                 `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyRequest) Reset() {
	*x = UpdateCompanyRequest{}
	mi := &file_company_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyRequest) ProtoMessage() {}

func (x *UpdateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCompanyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCompanyRequest) GetNameFormatUrl() string {
	if x != nil {
		return x.NameFormatUrl
	}
	return ""
}

func (x *UpdateCompanyRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyResponse) Reset() {
	*x = UpdateCompanyResponse{}
	mi := &file_company_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyResponse) ProtoMessage() {}

func (x *UpdateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyResponse.ProtoReflect.Descriptor instead.
func (*UpdateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCompanyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateCompanyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyRequest) Reset() {
	*x = DeleteCompanyRequest{}
	mi := &file_company_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyRequest) ProtoMessage() {}

func (x *DeleteCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCompanyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyResponse) Reset() {
	*x = DeleteCompanyResponse{}
	mi := &file_company_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyResponse) ProtoMessage() {}

func (x *DeleteCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyResponse.ProtoReflect.Descriptor instead.
func (*DeleteCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCompanyResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteCompanyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateCompanyImageUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyImageUrlRequest) Reset() {
	*x = UpdateCompanyImageUrlRequest{}
	mi := &file_company_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyImageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyImageUrlRequest) ProtoMessage() {}

func (x *UpdateCompanyImageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyImageUrlRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyImageUrlRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCompanyImageUrlRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCompanyImageUrlRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateCompanyImageUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyImageUrlResponse) Reset() {
	*x = UpdateCompanyImageUrlResponse{}
	mi := &file_company_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyImageUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyImageUrlResponse) ProtoMessage() {}

func (x *UpdateCompanyImageUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyImageUrlResponse.ProtoReflect.Descriptor instead.
func (*UpdateCompanyImageUrlResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCompanyImageUrlResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateCompanyImageUrlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_company_proto protoreflect.FileDescriptor

const file_company_proto_rawDesc = "" +
	"\n" +
	"\rcompany.proto\x12\acompany\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x14CreateCompanyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0fname_format_url\x18\x02 \x01(\tR\rnameFormatUrl\"U\n" +
	"\x15CreateCompanyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"#\n" +
	"\x11GetCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9b\x02\n" +
	"\x12GetCompanyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fname_format_url\x18\x03 \x01(\tR\rnameFormatUrl\x12\x1f\n" +
	"\bimageUrl\x18\x04 \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x17\n" +
	"\aplan_id\x18\x05 \x01(\x03R\x06planId\x12D\n" +
	"\x0flastPaymentDate\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastPaymentDate\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05errorB\v\n" +
	"\t_imageUrl\"-\n" +
	"\x17GetCompanyByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa1\x02\n" +
	"\x18GetCompanyByNameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fname_format_url\x18\x03 \x01(\tR\rnameFormatUrl\x12\x1f\n" +
	"\bimageUrl\x18\x04 \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x17\n" +
	"\aplan_id\x18\x05 \x01(\x03R\x06planId\x12D\n" +
	"\x0flastPaymentDate\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastPaymentDate\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05errorB\v\n" +
	"\t_imageUrl\"6\n" +
	"\x1aGetCompanyByNameUrlRequest\x12\x18\n" +
	"\anameUrl\x18\x01 \x01(\tR\anameUrl\"\xa4\x02\n" +
	"\x1bGetCompanyByNameUrlResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fname_format_url\x18\x03 \x01(\tR\rnameFormatUrl\x12\x1f\n" +
	"\bimageUrl\x18\x04 \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x17\n" +
	"\aplan_id\x18\x05 \x01(\x03R\x06planId\x12D\n" +
	"\x0flastPaymentDate\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastPaymentDate\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05errorB\v\n" +
	"\t_imageUrl\"C\n" +
	"\x13GetCompaniesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x7f\n" +
	"\x14GetCompaniesResponse\x129\n" +
	"\tcompanies\x18\x01 \x03(\v2\x1b.company.GetCompanyResponseR\tcompanies\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x87\x01\n" +
	"\x14UpdateCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fname_format_url\x18\x03 \x01(\tR\rnameFormatUrl\x12\x19\n" +
	"\x05image\x18\x04 \x01(\fH\x00R\x05image\x88\x01\x01B\b\n" +
	"\x06_image\"E\n" +
	"\x15UpdateCompanyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x14DeleteCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x15DeleteCompanyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x1cUpdateCompanyImageUrlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"M\n" +
	"\x1dUpdateCompanyImageUrlResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xb7\x05\n" +
	"\x0eCompanyService\x12N\n" +
	"\rCreateCompany\x12\x1d.company.CreateCompanyRequest\x1a\x1e.company.CreateCompanyResponse\x12E\n" +
	"\n" +
	"GetCompany\x12\x1a.company.GetCompanyRequest\x1a\x1b.company.GetCompanyResponse\x12W\n" +
	"\x10GetCompanyByName\x12 .company.GetCompanyByNameRequest\x1a!.company.GetCompanyByNameResponse\x12`\n" +
	"\x13GetCompanyByNameUrl\x12#.company.GetCompanyByNameUrlRequest\x1a$.company.GetCompanyByNameUrlResponse\x12K\n" +
	"\fGetCompanies\x12\x1c.company.GetCompaniesRequest\x1a\x1d.company.GetCompaniesResponse\x12N\n" +
	"\rUpdateCompany\x12\x1d.company.UpdateCompanyRequest\x1a\x1e.company.UpdateCompanyResponse\x12N\n" +
	"\rDeleteCompany\x12\x1d.company.DeleteCompanyRequest\x1a\x1e.company.DeleteCompanyResponse\x12f\n" +
	"\x15UpdateCompanyImageUrl\x12%.company.UpdateCompanyImageUrlRequest\x1a&.company.UpdateCompanyImageUrlResponseB\vZ\t./companyb\x06proto3"

var (
	file_company_proto_rawDescOnce sync.Once
	file_company_proto_rawDescData []byte
)

func file_company_proto_rawDescGZIP() []byte {
	file_company_proto_rawDescOnce.Do(func() {
		file_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)))
	})
	return file_company_proto_rawDescData
}

var file_company_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_company_proto_goTypes = []any{
	(*CreateCompanyRequest)(nil),          // 0: company.CreateCompanyRequest
	(*CreateCompanyResponse)(nil),         // 1: company.CreateCompanyResponse
	(*GetCompanyRequest)(nil),             // 2: company.GetCompanyRequest
	(*GetCompanyResponse)(nil),            // 3: company.GetCompanyResponse
	(*GetCompanyByNameRequest)(nil),       // 4: company.GetCompanyByNameRequest
	(*GetCompanyByNameResponse)(nil),      // 5: company.GetCompanyByNameResponse
	(*GetCompanyByNameUrlRequest)(nil),    // 6: company.GetCompanyByNameUrlRequest
	(*GetCompanyByNameUrlResponse)(nil),   // 7: company.GetCompanyByNameUrlResponse
	(*GetCompaniesRequest)(nil),           // 8: company.GetCompaniesRequest
	(*GetCompaniesResponse)(nil),          // 9: company.GetCompaniesResponse
	(*UpdateCompanyRequest)(nil),          // 10: company.UpdateCompanyRequest
	(*UpdateCompanyResponse)(nil),         // 11: company.UpdateCompanyResponse
	(*DeleteCompanyRequest)(nil),          // 12: company.DeleteCompanyRequest
	(*DeleteCompanyResponse)(nil),         // 13: company.DeleteCompanyResponse
	(*UpdateCompanyImageUrlRequest)(nil),  // 14: company.UpdateCompanyImageUrlRequest
	(*UpdateCompanyImageUrlResponse)(nil), // 15: company.UpdateCompanyImageUrlResponse
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
}
var file_company_proto_depIdxs = []int32{
	16, // 0: company.GetCompanyResponse.lastPaymentDate:type_name -> google.protobuf.Timestamp
	16, // 1: company.GetCompanyByNameResponse.lastPaymentDate:type_name -> google.protobuf.Timestamp
	16, // 2: company.GetCompanyByNameUrlResponse.lastPaymentDate:type_name -> google.protobuf.Timestamp
	3,  // 3: company.GetCompaniesResponse.companies:type_name -> company.GetCompanyResponse
	0,  // 4: company.CompanyService.CreateCompany:input_type -> company.CreateCompanyRequest
	2,  // 5: company.CompanyService.GetCompany:input_type -> company.GetCompanyRequest
	4,  // 6: company.CompanyService.GetCompanyByName:input_type -> company.GetCompanyByNameRequest
	6,  // 7: company.CompanyService.GetCompanyByNameUrl:input_type -> company.GetCompanyByNameUrlRequest
	8,  // 8: company.CompanyService.GetCompanies:input_type -> company.GetCompaniesRequest
	10, // 9: company.CompanyService.UpdateCompany:input_type -> company.UpdateCompanyRequest
	12, // 10: company.CompanyService.DeleteCompany:input_type -> company.DeleteCompanyRequest
	14, // 11: company.CompanyService.UpdateCompanyImageUrl:input_type -> company.UpdateCompanyImageUrlRequest
	1,  // 12: company.CompanyService.CreateCompany:output_type -> company.CreateCompanyResponse
	3,  // 13: company.CompanyService.GetCompany:output_type -> company.GetCompanyResponse
	5,  // 14: company.CompanyService.GetCompanyByName:output_type -> company.GetCompanyByNameResponse
	7,  // 15: company.CompanyService.GetCompanyByNameUrl:output_type -> company.GetCompanyByNameUrlResponse
	9,  // 16: company.CompanyService.GetCompanies:output_type -> company.GetCompaniesResponse
	11, // 17: company.CompanyService.UpdateCompany:output_type -> company.UpdateCompanyResponse
	13, // 18: company.CompanyService.DeleteCompany:output_type -> company.DeleteCompanyResponse
	15, // 19: company.CompanyService.UpdateCompanyImageUrl:output_type -> company.UpdateCompanyImageUrlResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_company_proto_init() }
func file_company_proto_init() {
	if File_company_proto != nil {
		return
	}
	file_company_proto_msgTypes[3].OneofWrappers = []any{}
	file_company_proto_msgTypes[5].OneofWrappers = []any{}
	file_company_proto_msgTypes[7].OneofWrappers = []any{}
	file_company_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_company_proto_goTypes,
		DependencyIndexes: file_company_proto_depIdxs,
		MessageInfos:      file_company_proto_msgTypes,
	}.Build()
	File_company_proto = out.File
	file_company_proto_goTypes = nil
	file_company_proto_depIdxs = nil
}
