// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: payment_type.proto

package payment_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentTypeRequest) Reset() {
	*x = GetPaymentTypeRequest{}
	mi := &file_payment_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentTypeRequest) ProtoMessage() {}

func (x *GetPaymentTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentTypeRequest) Descriptor() ([]byte, []int) {
	return file_payment_type_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImagePath     *string                `protobuf:"bytes,3,opt,name=imagePath,proto3,oneof" json:"imagePath,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentTypeResponse) Reset() {
	*x = GetPaymentTypeResponse{}
	mi := &file_payment_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentTypeResponse) ProtoMessage() {}

func (x *GetPaymentTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentTypeResponse) Descriptor() ([]byte, []int) {
	return file_payment_type_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentTypeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPaymentTypeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPaymentTypeResponse) GetImagePath() string {
	if x != nil && x.ImagePath != nil {
		return *x.ImagePath
	}
	return ""
}

func (x *GetPaymentTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPaymentTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPaymentTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentTypesRequest) Reset() {
	*x = GetPaymentTypesRequest{}
	mi := &file_payment_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentTypesRequest) ProtoMessage() {}

func (x *GetPaymentTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentTypesRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentTypesRequest) Descriptor() ([]byte, []int) {
	return file_payment_type_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentTypesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPaymentTypesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPaymentTypesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PaymentTypes  []*GetPaymentTypeResponse `protobuf:"bytes,1,rep,name=payment_types,json=paymentTypes,proto3" json:"payment_types,omitempty"`
	Status        int64                     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentTypesResponse) Reset() {
	*x = GetPaymentTypesResponse{}
	mi := &file_payment_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentTypesResponse) ProtoMessage() {}

func (x *GetPaymentTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentTypesResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentTypesResponse) Descriptor() ([]byte, []int) {
	return file_payment_type_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentTypesResponse) GetPaymentTypes() []*GetPaymentTypeResponse {
	if x != nil {
		return x.PaymentTypes
	}
	return nil
}

func (x *GetPaymentTypesResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPaymentTypesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_payment_type_proto protoreflect.FileDescriptor

const file_payment_type_proto_rawDesc = "" +
	"\n" +
	"\x12payment_type.proto\x12\fpayment_type\"'\n" +
	"\x15GetPaymentTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9b\x01\n" +
	"\x16GetPaymentTypeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\timagePath\x18\x03 \x01(\tH\x00R\timagePath\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB\f\n" +
	"\n" +
	"_imagePath\"F\n" +
	"\x16GetPaymentTypesRequest\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x92\x01\n" +
	"\x17GetPaymentTypesResponse\x12I\n" +
	"\rpayment_types\x18\x01 \x03(\v2$.payment_type.GetPaymentTypeResponseR\fpaymentTypes\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xd1\x01\n" +
	"\x12PaymentTypeService\x12[\n" +
	"\x0eGetPaymentType\x12#.payment_type.GetPaymentTypeRequest\x1a$.payment_type.GetPaymentTypeResponse\x12^\n" +
	"\x0fGetPaymentTypes\x12$.payment_type.GetPaymentTypesRequest\x1a%.payment_type.GetPaymentTypesResponseB\x10Z\x0e./payment_typeb\x06proto3"

var (
	file_payment_type_proto_rawDescOnce sync.Once
	file_payment_type_proto_rawDescData []byte
)

func file_payment_type_proto_rawDescGZIP() []byte {
	file_payment_type_proto_rawDescOnce.Do(func() {
		file_payment_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_type_proto_rawDesc), len(file_payment_type_proto_rawDesc)))
	})
	return file_payment_type_proto_rawDescData
}

var file_payment_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_type_proto_goTypes = []any{
	(*GetPaymentTypeRequest)(nil),   // 0: payment_type.GetPaymentTypeRequest
	(*GetPaymentTypeResponse)(nil),  // 1: payment_type.GetPaymentTypeResponse
	(*GetPaymentTypesRequest)(nil),  // 2: payment_type.GetPaymentTypesRequest
	(*GetPaymentTypesResponse)(nil), // 3: payment_type.GetPaymentTypesResponse
}
var file_payment_type_proto_depIdxs = []int32{
	1, // 0: payment_type.GetPaymentTypesResponse.payment_types:type_name -> payment_type.GetPaymentTypeResponse
	0, // 1: payment_type.PaymentTypeService.GetPaymentType:input_type -> payment_type.GetPaymentTypeRequest
	2, // 2: payment_type.PaymentTypeService.GetPaymentTypes:input_type -> payment_type.GetPaymentTypesRequest
	1, // 3: payment_type.PaymentTypeService.GetPaymentType:output_type -> payment_type.GetPaymentTypeResponse
	3, // 4: payment_type.PaymentTypeService.GetPaymentTypes:output_type -> payment_type.GetPaymentTypesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_type_proto_init() }
func file_payment_type_proto_init() {
	if File_payment_type_proto != nil {
		return
	}
	file_payment_type_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_type_proto_rawDesc), len(file_payment_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_type_proto_goTypes,
		DependencyIndexes: file_payment_type_proto_depIdxs,
		MessageInfos:      file_payment_type_proto_msgTypes,
	}.Build()
	File_payment_type_proto = out.File
	file_payment_type_proto_goTypes = nil
	file_payment_type_proto_depIdxs = nil
}
