// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: whatsapp.proto

package whatsapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendOrderCustomerMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=companyId,proto3" json:"companyId,omitempty"`
	ToPhone       string                 `protobuf:"bytes,2,opt,name=toPhone,proto3" json:"toPhone,omitempty"`
	CustomerName  string                 `protobuf:"bytes,3,opt,name=customerName,proto3" json:"customerName,omitempty"`
	Products      []*OrderProductRequest `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderCustomerMessageRequest) Reset() {
	*x = SendOrderCustomerMessageRequest{}
	mi := &file_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderCustomerMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderCustomerMessageRequest) ProtoMessage() {}

func (x *SendOrderCustomerMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderCustomerMessageRequest.ProtoReflect.Descriptor instead.
func (*SendOrderCustomerMessageRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{0}
}

func (x *SendOrderCustomerMessageRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *SendOrderCustomerMessageRequest) GetToPhone() string {
	if x != nil {
		return x.ToPhone
	}
	return ""
}

func (x *SendOrderCustomerMessageRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *SendOrderCustomerMessageRequest) GetProducts() []*OrderProductRequest {
	if x != nil {
		return x.Products
	}
	return nil
}

type SendOrderCustomerMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderCustomerMessageResponse) Reset() {
	*x = SendOrderCustomerMessageResponse{}
	mi := &file_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderCustomerMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderCustomerMessageResponse) ProtoMessage() {}

func (x *SendOrderCustomerMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderCustomerMessageResponse.ProtoReflect.Descriptor instead.
func (*SendOrderCustomerMessageResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *SendOrderCustomerMessageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendOrderCustomerMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendOrderBusinessMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customerName,proto3" json:"customerName,omitempty"`
	ContactNumber string                 `protobuf:"bytes,3,opt,name=contactNumber,proto3" json:"contactNumber,omitempty"`
	Products      []*OrderProductRequest `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderBusinessMessageRequest) Reset() {
	*x = SendOrderBusinessMessageRequest{}
	mi := &file_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderBusinessMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderBusinessMessageRequest) ProtoMessage() {}

func (x *SendOrderBusinessMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderBusinessMessageRequest.ProtoReflect.Descriptor instead.
func (*SendOrderBusinessMessageRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *SendOrderBusinessMessageRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *SendOrderBusinessMessageRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *SendOrderBusinessMessageRequest) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *SendOrderBusinessMessageRequest) GetProducts() []*OrderProductRequest {
	if x != nil {
		return x.Products
	}
	return nil
}

type SendOrderBusinessMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderBusinessMessageResponse) Reset() {
	*x = SendOrderBusinessMessageResponse{}
	mi := &file_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderBusinessMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderBusinessMessageResponse) ProtoMessage() {}

func (x *SendOrderBusinessMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderBusinessMessageResponse.ProtoReflect.Descriptor instead.
func (*SendOrderBusinessMessageResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *SendOrderBusinessMessageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendOrderBusinessMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OrderProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProductRequest) Reset() {
	*x = OrderProductRequest{}
	mi := &file_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductRequest) ProtoMessage() {}

func (x *OrderProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductRequest.ProtoReflect.Descriptor instead.
func (*OrderProductRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *OrderProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderProductRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderProductRequest) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateBusinessPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusinessPhoneRequest) Reset() {
	*x = CreateBusinessPhoneRequest{}
	mi := &file_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusinessPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessPhoneRequest) ProtoMessage() {}

func (x *CreateBusinessPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessPhoneRequest.ProtoReflect.Descriptor instead.
func (*CreateBusinessPhoneRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBusinessPhoneRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *CreateBusinessPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateBusinessPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusinessPhoneResponse) Reset() {
	*x = CreateBusinessPhoneResponse{}
	mi := &file_whatsapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusinessPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessPhoneResponse) ProtoMessage() {}

func (x *CreateBusinessPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessPhoneResponse.ProtoReflect.Descriptor instead.
func (*CreateBusinessPhoneResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBusinessPhoneResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateBusinessPhoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateBusinessPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessPhoneRequest) Reset() {
	*x = UpdateBusinessPhoneRequest{}
	mi := &file_whatsapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessPhoneRequest) ProtoMessage() {}

func (x *UpdateBusinessPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessPhoneRequest.ProtoReflect.Descriptor instead.
func (*UpdateBusinessPhoneRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBusinessPhoneRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UpdateBusinessPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateBusinessPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessPhoneResponse) Reset() {
	*x = UpdateBusinessPhoneResponse{}
	mi := &file_whatsapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessPhoneResponse) ProtoMessage() {}

func (x *UpdateBusinessPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessPhoneResponse.ProtoReflect.Descriptor instead.
func (*UpdateBusinessPhoneResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBusinessPhoneResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateBusinessPhoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBusinessPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessPhoneRequest) Reset() {
	*x = GetBusinessPhoneRequest{}
	mi := &file_whatsapp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessPhoneRequest) ProtoMessage() {}

func (x *GetBusinessPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessPhoneRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{9}
}

func (x *GetBusinessPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetBusinessPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     int64                  `protobuf:"varint,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessPhoneResponse) Reset() {
	*x = GetBusinessPhoneResponse{}
	mi := &file_whatsapp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessPhoneResponse) ProtoMessage() {}

func (x *GetBusinessPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessPhoneResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{10}
}

func (x *GetBusinessPhoneResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBusinessPhoneResponse) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetBusinessPhoneResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetBusinessPhoneResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetBusinessPhoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBusinessPhoneByCompanyIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=companyId,proto3" json:"companyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessPhoneByCompanyIdRequest) Reset() {
	*x = GetBusinessPhoneByCompanyIdRequest{}
	mi := &file_whatsapp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessPhoneByCompanyIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessPhoneByCompanyIdRequest) ProtoMessage() {}

func (x *GetBusinessPhoneByCompanyIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessPhoneByCompanyIdRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessPhoneByCompanyIdRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{11}
}

func (x *GetBusinessPhoneByCompanyIdRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

type GetBusinessPhoneByCompanyIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     int64                  `protobuf:"varint,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessPhoneByCompanyIdResponse) Reset() {
	*x = GetBusinessPhoneByCompanyIdResponse{}
	mi := &file_whatsapp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessPhoneByCompanyIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessPhoneByCompanyIdResponse) ProtoMessage() {}

func (x *GetBusinessPhoneByCompanyIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessPhoneByCompanyIdResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessPhoneByCompanyIdResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{12}
}

func (x *GetBusinessPhoneByCompanyIdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBusinessPhoneByCompanyIdResponse) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetBusinessPhoneByCompanyIdResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetBusinessPhoneByCompanyIdResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetBusinessPhoneByCompanyIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_whatsapp_proto protoreflect.FileDescriptor

const file_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x0ewhatsapp.proto\x12\bwhatsapp\"\xb8\x01\n" +
	"\x1fSendOrderCustomerMessageRequest\x12\x1c\n" +
	"\tcompanyId\x18\x01 \x01(\x03R\tcompanyId\x12\x18\n" +
	"\atoPhone\x18\x02 \x01(\tR\atoPhone\x12\"\n" +
	"\fcustomerName\x18\x03 \x01(\tR\fcustomerName\x129\n" +
	"\bproducts\x18\x04 \x03(\v2\x1d.whatsapp.OrderProductRequestR\bproducts\"P\n" +
	" SendOrderCustomerMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc4\x01\n" +
	"\x1fSendOrderBusinessMessageRequest\x12\x1c\n" +
	"\tcompanyId\x18\x01 \x01(\x03R\tcompanyId\x12\"\n" +
	"\fcustomerName\x18\x02 \x01(\tR\fcustomerName\x12$\n" +
	"\rcontactNumber\x18\x03 \x01(\tR\rcontactNumber\x129\n" +
	"\bproducts\x18\x04 \x03(\v2\x1d.whatsapp.OrderProductRequestR\bproducts\"P\n" +
	" SendOrderBusinessMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"[\n" +
	"\x13OrderProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\"P\n" +
	"\x1aCreateBusinessPhoneRequest\x12\x1c\n" +
	"\tcompanyId\x18\x01 \x01(\x03R\tcompanyId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"K\n" +
	"\x1bCreateBusinessPhoneResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"P\n" +
	"\x1aUpdateBusinessPhoneRequest\x12\x1c\n" +
	"\tcompanyId\x18\x01 \x01(\x03R\tcompanyId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"K\n" +
	"\x1bUpdateBusinessPhoneResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x17GetBusinessPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"\x8c\x01\n" +
	"\x18GetBusinessPhoneResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcompanyId\x18\x02 \x01(\x03R\tcompanyId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"B\n" +
	"\"GetBusinessPhoneByCompanyIdRequest\x12\x1c\n" +
	"\tcompanyId\x18\x01 \x01(\x03R\tcompanyId\"\x97\x01\n" +
	"#GetBusinessPhoneByCompanyIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcompanyId\x18\x02 \x01(\x03R\tcompanyId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\x96\x05\n" +
	"\x0fWhatsappService\x12q\n" +
	"\x18SendOrderCustomerMessage\x12).whatsapp.SendOrderCustomerMessageRequest\x1a*.whatsapp.SendOrderCustomerMessageResponse\x12q\n" +
	"\x18SendOrderBusinessMessage\x12).whatsapp.SendOrderBusinessMessageRequest\x1a*.whatsapp.SendOrderBusinessMessageResponse\x12b\n" +
	"\x13CreateBusinessPhone\x12$.whatsapp.CreateBusinessPhoneRequest\x1a%.whatsapp.CreateBusinessPhoneResponse\x12b\n" +
	"\x13UpdateBusinessPhone\x12$.whatsapp.UpdateBusinessPhoneRequest\x1a%.whatsapp.UpdateBusinessPhoneResponse\x12Y\n" +
	"\x10GetBusinessPhone\x12!.whatsapp.GetBusinessPhoneRequest\x1a\".whatsapp.GetBusinessPhoneResponse\x12z\n" +
	"\x1bGetBusinessPhoneByCompanyId\x12,.whatsapp.GetBusinessPhoneByCompanyIdRequest\x1a-.whatsapp.GetBusinessPhoneByCompanyIdResponseB\fZ\n" +
	"./whatsappb\x06proto3"

var (
	file_whatsapp_proto_rawDescOnce sync.Once
	file_whatsapp_proto_rawDescData []byte
)

func file_whatsapp_proto_rawDescGZIP() []byte {
	file_whatsapp_proto_rawDescOnce.Do(func() {
		file_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whatsapp_proto_rawDesc), len(file_whatsapp_proto_rawDesc)))
	})
	return file_whatsapp_proto_rawDescData
}

var file_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_whatsapp_proto_goTypes = []any{
	(*SendOrderCustomerMessageRequest)(nil),     // 0: whatsapp.SendOrderCustomerMessageRequest
	(*SendOrderCustomerMessageResponse)(nil),    // 1: whatsapp.SendOrderCustomerMessageResponse
	(*SendOrderBusinessMessageRequest)(nil),     // 2: whatsapp.SendOrderBusinessMessageRequest
	(*SendOrderBusinessMessageResponse)(nil),    // 3: whatsapp.SendOrderBusinessMessageResponse
	(*OrderProductRequest)(nil),                 // 4: whatsapp.OrderProductRequest
	(*CreateBusinessPhoneRequest)(nil),          // 5: whatsapp.CreateBusinessPhoneRequest
	(*CreateBusinessPhoneResponse)(nil),         // 6: whatsapp.CreateBusinessPhoneResponse
	(*UpdateBusinessPhoneRequest)(nil),          // 7: whatsapp.UpdateBusinessPhoneRequest
	(*UpdateBusinessPhoneResponse)(nil),         // 8: whatsapp.UpdateBusinessPhoneResponse
	(*GetBusinessPhoneRequest)(nil),             // 9: whatsapp.GetBusinessPhoneRequest
	(*GetBusinessPhoneResponse)(nil),            // 10: whatsapp.GetBusinessPhoneResponse
	(*GetBusinessPhoneByCompanyIdRequest)(nil),  // 11: whatsapp.GetBusinessPhoneByCompanyIdRequest
	(*GetBusinessPhoneByCompanyIdResponse)(nil), // 12: whatsapp.GetBusinessPhoneByCompanyIdResponse
}
var file_whatsapp_proto_depIdxs = []int32{
	4,  // 0: whatsapp.SendOrderCustomerMessageRequest.products:type_name -> whatsapp.OrderProductRequest
	4,  // 1: whatsapp.SendOrderBusinessMessageRequest.products:type_name -> whatsapp.OrderProductRequest
	0,  // 2: whatsapp.WhatsappService.SendOrderCustomerMessage:input_type -> whatsapp.SendOrderCustomerMessageRequest
	2,  // 3: whatsapp.WhatsappService.SendOrderBusinessMessage:input_type -> whatsapp.SendOrderBusinessMessageRequest
	5,  // 4: whatsapp.WhatsappService.CreateBusinessPhone:input_type -> whatsapp.CreateBusinessPhoneRequest
	7,  // 5: whatsapp.WhatsappService.UpdateBusinessPhone:input_type -> whatsapp.UpdateBusinessPhoneRequest
	9,  // 6: whatsapp.WhatsappService.GetBusinessPhone:input_type -> whatsapp.GetBusinessPhoneRequest
	11, // 7: whatsapp.WhatsappService.GetBusinessPhoneByCompanyId:input_type -> whatsapp.GetBusinessPhoneByCompanyIdRequest
	1,  // 8: whatsapp.WhatsappService.SendOrderCustomerMessage:output_type -> whatsapp.SendOrderCustomerMessageResponse
	3,  // 9: whatsapp.WhatsappService.SendOrderBusinessMessage:output_type -> whatsapp.SendOrderBusinessMessageResponse
	6,  // 10: whatsapp.WhatsappService.CreateBusinessPhone:output_type -> whatsapp.CreateBusinessPhoneResponse
	8,  // 11: whatsapp.WhatsappService.UpdateBusinessPhone:output_type -> whatsapp.UpdateBusinessPhoneResponse
	10, // 12: whatsapp.WhatsappService.GetBusinessPhone:output_type -> whatsapp.GetBusinessPhoneResponse
	12, // 13: whatsapp.WhatsappService.GetBusinessPhoneByCompanyId:output_type -> whatsapp.GetBusinessPhoneByCompanyIdResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_whatsapp_proto_init() }
func file_whatsapp_proto_init() {
	if File_whatsapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatsapp_proto_rawDesc), len(file_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whatsapp_proto_goTypes,
		DependencyIndexes: file_whatsapp_proto_depIdxs,
		MessageInfos:      file_whatsapp_proto_msgTypes,
	}.Build()
	File_whatsapp_proto = out.File
	file_whatsapp_proto_goTypes = nil
	file_whatsapp_proto_depIdxs = nil
}
