volumes:
  customer_db_data:
    name: customer_db_data
  company_db_data:
    name: company_db_data
  product_db_data:
    name: product_db_data
  whatsapp_db_data:
    name: whatsapp_db_data
  auth_db_data:
    name: auth_db_data

services:
  # nginx:
  #   image: nginx:1.27.3
  #   container_name: business-manager-nginx-proxy
  #   volumes:
  #     - /home/edorguez/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - /home/edorguez/nginx/certs:/etc/nginx/certs:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - my_app_network
  #   restart: always
  #
  # ui:
  #   container_name: edezco
  #   image: edorguez/ui-business-manager
  #   ports:
  #     - "${UI_PORT}:${UI_PORT}"
  #   build:
  #     context: ./nextjs-app
  #   environment:
  #     - ENVIRONMENT=production
  #     - NEXT_PUBLIC_ENVIRONMENT=production
  #   networks:
  #     - my_app_network
  #   depends_on:
  #     - gateway
  #   restart: always

  gateway:
    container_name: gateway
    image: edorguez/gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - ENVIRONMENT=production
      - PRODUCTION_URL=${PRODUCTION_URL}
      - DEVELOPMENT_URL=${DEVELOPMENT_URL}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - CUSTOMER_SVC_URL=${CUSTOMER_SVC_URL}
      - CUSTOMER_SVC_PORT=${CUSTOMER_SVC_PORT}
      - COMPANY_SVC_URL=${COMPANY_SVC_URL}
      - COMPANY_SVC_PORT=${COMPANY_SVC_PORT}
      - PRODUCT_SVC_URL=${PRODUCT_SVC_URL}
      - PRODUCT_SVC_PORT=${PRODUCT_SVC_PORT}
      - AUTH_SVC_URL=${AUTH_SVC_URL}
      - AUTH_SVC_PORT=${AUTH_SVC_PORT}
      - ORDER_SVC_URL=${ORDER_SVC_URL}
      - ORDER_SVC_PORT=${ORDER_SVC_PORT}
      - FILE_SVC_URL=${FILE_SVC_URL}
      - FILE_SVC_PORT=${FILE_SVC_PORT}
      - WHATSAPP_SVC_URL=${WHATSAPP_SVC_URL}
      - WHATSAPP_SVC_PORT=${WHATSAPP_SVC_PORT}
    networks:
      - my_app_network
    restart: always

  customer-svc:
      container_name: customer-svc
      image: edorguez/customer-svc
      ports:
        - "${CUSTOMER_SVC_PORT}:${CUSTOMER_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - CUSTOMER_SVC_PORT=${CUSTOMER_SVC_PORT}
        - POSTGRES_DB_DRIVER=${POSTGRES_DB_DRIVER}
        - CUSTOMER_DB_SOURCE_DEVELOPMENT=${CUSTOMER_DB_SOURCE_DEVELOPMENT}
        - CUSTOMER_DB_SOURCE_PRODUCTION=${CUSTOMER_DB_SOURCE_PRODUCTION}
      networks:
        - my_app_network
      depends_on:
        - customer-db
      restart: always

  company-svc:
      container_name: company-svc
      image: edorguez/company-svc
      ports:
        - "${COMPANY_SVC_PORT}:${COMPANY_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - COMPANY_SVC_PORT=${COMPANY_SVC_PORT}
        - POSTGRES_DB_DRIVER=${POSTGRES_DB_DRIVER}
        - COMPANY_DB_SOURCE_DEVELOPMENT=${COMPANY_DB_SOURCE_DEVELOPMENT}
        - COMPANY_DB_SOURCE_PRODUCTION=${COMPANY_DB_SOURCE_PRODUCTION}
        - FILE_SVC_URL=${FILE_SVC_URL}
        - FILE_SVC_PORT=${FILE_SVC_PORT}
      networks:
        - my_app_network
      depends_on:
        - company-db
      restart: always

  product-svc:
      container_name: product-svc
      image: edorguez/product-svc
      ports:
        - "${PRODUCT_SVC_PORT}:${PRODUCT_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - PRODUCT_SVC_PORT=${PRODUCT_SVC_PORT}
        - PRODUCT_DB_NAME=${PRODUCT_DB_NAME}
        - PRODUCT_DB_SOURCE_DEVELOPMENT=${PRODUCT_DB_SOURCE_DEVELOPMENT}
        - PRODUCT_DB_SOURCE_PRODUCTION=${PRODUCT_DB_SOURCE_PRODUCTION}
        - COMPANY_SVC_URL=${COMPANY_SVC_URL}
        - COMPANY_SVC_PORT=${COMPANY_SVC_PORT}
        - FILE_SVC_URL=${FILE_SVC_URL}
        - FILE_SVC_PORT=${FILE_SVC_PORT}
      networks:
        - my_app_network
      depends_on:
        - product-db
      restart: always

  whatsapp-svc:
      container_name: whatsapp-svc
      image: edorguez/whatsapp-svc
      ports:
        - "${WHATSAPP_SVC_PORT}:${WHATSAPP_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - WHATSAPP_SVC_PORT=${WHATSAPP_SVC_PORT}
        - POSTGRES_DB_DRIVER=${POSTGRES_DB_DRIVER}
        - WHATSAPP_DB_SOURCE_DEVELOPMENT=${WHATSAPP_DB_SOURCE_DEVELOPMENT}
        - WHATSAPP_DB_SOURCE_PRODUCTION=${WHATSAPP_DB_SOURCE_PRODUCTION}
        - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
        - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
        - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      networks:
        - my_app_network
      depends_on:
        - whatsapp-db
      restart: always

  auth-svc:
      container_name: auth-svc
      image: edorguez/auth-svc
      ports:
        - "${AUTH_SVC_PORT}:${AUTH_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - AUTH_SVC_PORT=${AUTH_SVC_PORT}
        - POSTGRES_DB_DRIVER=${POSTGRES_DB_DRIVER}
        - AUTH_DB_SOURCE_DEVELOPMENT=${AUTH_DB_SOURCE_DEVELOPMENT}
        - AUTH_DB_SOURCE_PRODUCTION=${AUTH_DB_SOURCE_PRODUCTION}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        - COMPANY_SVC_URL=${COMPANY_SVC_URL}
        - COMPANY_SVC_PORT=${COMPANY_SVC_PORT}
      networks:
        - my_app_network
      depends_on:
        - auth-db
      restart: always

  order-svc:
      container_name: order-svc
      image: edorguez/order-svc
      ports:
        - "${ORDER_SVC_PORT}:${ORDER_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - ORDER_SVC_PORT=${ORDER_SVC_PORT}
        - CUSTOMER_SVC_URL=${CUSTOMER_SVC_URL}
        - CUSTOMER_SVC_PORT=${CUSTOMER_SVC_PORT}
        - WHATSAPP_SVC_URL=${WHATSAPP_SVC_URL}
        - WHATSAPP_SVC_PORT=${WHATSAPP_SVC_PORT}
      networks:
        - my_app_network
      restart: always

  file-svc:
      container_name: file-svc
      image: edorguez/file-svc
      ports:
        - "${FILE_SVC_PORT}:${FILE_SVC_PORT}"
      environment:
        - ENVIRONMENT=production
        - FILE_SVC_PORT=${FILE_SVC_PORT}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY_ID}
      networks:
        - my_app_network
      restart: always

  customer-db:
    container_name: customer-db
    image: postgres:16.2
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${CUSTOMER_SVC_DB}
      - POSTGRES_USER=${CUSTOMER_SVC_DB_USER}
      - POSTGRES_PASSWORD=${CUSTOMER_SVC_DB_PASSWORD}
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    networks:
        - my_app_network
    restart: always

  company-db:
    container_name: company-db
    image: postgres:16.2
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=${COMPANY_SVC_DB}
      - POSTGRES_USER=${COMPANY_SVC_DB_USER}
      - POSTGRES_PASSWORD=${COMPANY_SVC_DB_PASSWORD}
    volumes:
      - company_db_data:/var/lib/postgresql/data
    networks:
        - my_app_network
    restart: always

  product-db:
    container_name: product-db
    image: mongo:7.0.8
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PRODUCT_SVC_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${PRODUCT_SVC_DB_PASSWORD}
    volumes:
      - product_db_data:/data/db
    networks:
        - my_app_network
    restart: always

  whatsapp-db:
    container_name: whatsapp-db
    image: postgres:16.2
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=${WHATSAPP_SVC_DB}
      - POSTGRES_USER=${WHATSAPP_SVC_DB_USER}
      - POSTGRES_PASSWORD=${WHATSAPP_SVC_DB_PASSWORD}
    volumes:
      - whatsapp_db_data:/var/lib/postgresql/data
    networks:
        - my_app_network
    restart: always

  auth-db:
    container_name: auth-db
    image: postgres:16.2
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=${AUTH_SVC_DB}
      - POSTGRES_USER=${AUTH_SVC_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_SVC_DB_PASSWORD}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
        - my_app_network
    restart: always

networks:
  my_app_network:
    name: my_app_network
