apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-svc
  template:
    metadata:
      labels:
        app: company-svc
    spec:
      containers:
        - name: company-svc
          image: edorguez/company-svc
          ports:
            - containerPort: 50053
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: company-svc
spec:
  selector:
    app: company-svc
  ports:
    - port: 50053
      name: grpc
      targetPort: 50053
  type: ClusterIP
