apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-svc
  template:
    metadata:
      labels:
        app: customer-svc
    spec:
      containers:
        - name: customer-svc
          image: edorguez/customer-svc
          ports:
            - containerPort: 50052
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector:
    app: customer-svc
  ports:
    - port: 50052
      name: grpc
      targetPort: 50052
  type: ClusterIP
