apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-svc
  template:
    metadata:
      labels:
        app: file-svc
    spec:
      containers:
        - name: file-svc
          image: edorguez/file-svc
          ports:
            - containerPort: 50058
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: file-svc
spec:
  selector:
    app: file-svc
  ports:
    - port: 50058
      name: grpc
      targetPort: 50058
  type: ClusterIP
