// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type CompanyCompany struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	ImageUrl   sql.NullString `json:"image_url"`
	CreatedAt  time.Time      `json:"created_at"`
	ModifiedAt time.Time      `json:"modified_at"`
}

type CompanyPayment struct {
	ID                   int64          `json:"id"`
	CompanyID            int64          `json:"company_id"`
	Name                 string         `json:"name"`
	Bank                 sql.NullString `json:"bank"`
	AccountNumber        sql.NullString `json:"account_number"`
	AccountType          sql.NullString `json:"account_type"`
	IdentificationNumber sql.NullString `json:"identification_number"`
	IdentificationType   sql.NullString `json:"identification_type"`
	Phone                sql.NullString `json:"phone"`
	Email                sql.NullString `json:"email"`
	PaymentTypeID        int64          `json:"payment_type_id"`
	CreatedAt            time.Time      `json:"created_at"`
	ModifiedAt           time.Time      `json:"modified_at"`
}

type CompanyPaymentType struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
}
