// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (CompanyCompany, error)
	DeleteCompany(ctx context.Context, id int64) error
	GetCompanies(ctx context.Context, arg GetCompaniesParams) ([]CompanyCompany, error)
	GetCompany(ctx context.Context, id int64) (CompanyCompany, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (CompanyCompany, error)
}

var _ Querier = (*Queries)(nil)
