// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type OrderOrder struct {
	ID          int64     `json:"id"`
	CompanyID   int64     `json:"company_id"`
	CustomerID  int64     `json:"customer_id"`
	OrderNumber int32     `json:"order_number"`
	CreatedAt   time.Time `json:"created_at"`
	ModifiedAt  time.Time `json:"modified_at"`
}

type OrderOrderProduct struct {
	ID         int64          `json:"id"`
	OrderID    int64          `json:"order_id"`
	ProductID  string         `json:"product_id"`
	Quantity   int32          `json:"quantity"`
	Price      int64          `json:"price"`
	Name       string         `json:"name"`
	ImageUrl   sql.NullString `json:"image_url"`
	CreatedAt  time.Time      `json:"created_at"`
	ModifiedAt time.Time      `json:"modified_at"`
}
