// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order"."order" (company_id, customer_id)
VALUES ($1, $2)
RETURNING id, company_id, customer_id, created_at, modified_at
`

type CreateOrderParams struct {
	CompanyID  int64 `json:"company_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (OrderOrder, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.CompanyID, arg.CustomerID)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, company_id, customer_id, created_at, modified_at FROM "order"."order" WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (OrderOrder, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT id, company_id, customer_id, created_at, modified_at FROM "order"."order"
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrdersParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetOrders(ctx context.Context, arg GetOrdersParams) ([]OrderOrder, error) {
	rows, err := q.db.QueryContext(ctx, getOrders, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrder{}
	for rows.Next() {
		var i OrderOrder
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersCount = `-- name: GetOrdersCount :one
SELECT COUNT(*) FROM "order"."order" WHERE company_id = $1
`

func (q *Queries) GetOrdersCount(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrdersCount, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
