// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order"."order" (company_id, customer_id, order_number)
VALUES ($1, $2, $3)
RETURNING id, company_id, customer_id, order_number, created_at, modified_at
`

type CreateOrderParams struct {
	CompanyID   int64 `json:"company_id"`
	CustomerID  int64 `json:"customer_id"`
	OrderNumber int32 `json:"order_number"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (OrderOrder, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.CompanyID, arg.CustomerID, arg.OrderNumber)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getMaxOrderNumberForCompany = `-- name: GetMaxOrderNumberForCompany :one
SELECT COALESCE(MAX(order_number), 0)::INTEGER as max_order_number 
FROM "order"."order" 
WHERE company_id = $1
`

func (q *Queries) GetMaxOrderNumberForCompany(ctx context.Context, companyID int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxOrderNumberForCompany, companyID)
	var max_order_number int32
	err := row.Scan(&max_order_number)
	return max_order_number, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, company_id, customer_id, order_number, created_at, modified_at FROM "order"."order" WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (OrderOrder, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i OrderOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT id, company_id, customer_id, order_number, created_at, modified_at FROM "order"."order"
WHERE company_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type GetOrdersParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetOrders(ctx context.Context, arg GetOrdersParams) ([]OrderOrder, error) {
	rows, err := q.db.QueryContext(ctx, getOrders, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrder{}
	for rows.Next() {
		var i OrderOrder
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByMonth = `-- name: GetOrdersByMonth :many
SELECT created_at
FROM "order"."order"
WHERE company_id = $1
  AND created_at >= make_date($2::int, $3::int, 1)
  AND created_at < make_date($2::int, $3::int, 1) + INTERVAL '1 month'
ORDER BY created_at
`

type GetOrdersByMonthParams struct {
	CompanyID int64 `json:"company_id"`
	Year      int32 `json:"year"`
	Month     int32 `json:"month"`
}

func (q *Queries) GetOrdersByMonth(ctx context.Context, arg GetOrdersByMonthParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByMonth, arg.CompanyID, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var created_at time.Time
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersCount = `-- name: GetOrdersCount :one
SELECT COUNT(*) FROM "order"."order" WHERE company_id = $1
`

func (q *Queries) GetOrdersCount(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrdersCount, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lockCompanyOrders = `-- name: LockCompanyOrders :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) LockCompanyOrders(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.ExecContext(ctx, lockCompanyOrders, pgAdvisoryXactLock)
	return err
}
