// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_product.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrderProduct = `-- name: CreateOrderProduct :one
INSERT INTO "order"."order_product" (order_id, product_id, quantity, price, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, created_at, modified_at, quantity, price, name
`

type CreateOrderProductParams struct {
	OrderID   int64     `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	Price     int64     `json:"price"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (OrderOrderProduct, error) {
	row := q.db.QueryRowContext(ctx, createOrderProduct,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.Name,
	)
	var i OrderOrderProduct
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Quantity,
		&i.Price,
		&i.Name,
	)
	return i, err
}

const getOrderProductsByOrderId = `-- name: GetOrderProductsByOrderId :many
SELECT id, order_id, product_id, created_at, modified_at, quantity, price, name FROM "order"."order_product" WHERE order_id = $1 ORDER BY id
`

func (q *Queries) GetOrderProductsByOrderId(ctx context.Context, orderID int64) ([]OrderOrderProduct, error) {
	rows, err := q.db.QueryContext(ctx, getOrderProductsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrderProduct{}
	for rows.Next() {
		var i OrderOrderProduct
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Quantity,
			&i.Price,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
