// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	DeleteUser(ctx context.Context, id int64) error
	GetRole(ctx context.Context, id int64) (AuthRole, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]AuthRole, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (AuthUser, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (AuthUser, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (AuthUser, error)
}

var _ Querier = (*Queries)(nil)
